local mod = get_mod("extended_weapon_customization_owo")

return {
	name = mod:localize("mod_name"),
	description = mod:localize("mod_description"),
	is_togglable = true,
	options = {
		widgets = {
            {   setting_id = "debug_mode",
                type = "checkbox",
                default_value = false,
            },
            {   setting_id = "owo_mode",
                type = "checkbox",
                default_value = false,
            },
            {   setting_id = "discord_mode",
                type = "checkbox",
                default_value = false,
            },
            {   setting_id = "group_randomization_options",
                type = "group",
                sub_widgets = {
                    {   setting_id = "mod_option_empty_randomization",
                        type = "checkbox",
                        default_value = false,
                    },
                },
            },
            {   setting_id = "group_randomization_options_ranged",
                type = "group",
                sub_widgets = {
                    {   setting_id = "group_randomization_options_sight",
                        type = "group",
                        sub_widgets = {
                            {   setting_id = "mod_option_holographic_sight_randomization",
                                type = "checkbox",
                                default_value = true,
                            },
                            {   setting_id = "mod_option_iron_sight_randomization",
                                type = "checkbox",
                                default_value = true,
                            },
                            {   setting_id = "mod_option_sight_reticle_randomization",
                                type = "checkbox",
                                default_value = false,
                            },
                        },
                    },
                    {   setting_id = "group_randomization_options_barrel",
                        type = "group",
                        sub_widgets = {
                            {   setting_id = "mod_option_modern_barrel_randomization",
                                type = "checkbox",
                                default_value = true,
                            },
                        },
                    },
                    {   setting_id = "group_randomization_options_muzzle",
                        type = "group",
                        sub_widgets = {
                            {   setting_id = "mod_option_suppressor_randomization",
                                type = "checkbox",
                                default_value = true,
                            },
                        },
                    },
                    {   setting_id = "group_randomization_options_stock",
                        type = "group",
                        sub_widgets = {
                            {   setting_id = "mod_option_tactical_stock_randomization",
                                type = "checkbox",
                                default_value = true,
                            },
                        },
                    },
                    {   setting_id = "group_randomization_options_other_ranged",
                        type = "group",
                        sub_widgets = {
                            {   setting_id = "mod_option_flashlight_randomization",
                                type = "checkbox",
                                default_value = false,
                            },
                            {   setting_id = "mod_option_magazine_randomization",
                                type = "checkbox",
                                default_value = true,
                            }, 
                            {   setting_id = "mod_option_underbarrel_laspistol_randomization",
                                type = "checkbox",
                                default_value = false,
                            },
                        },
                    },
                },
            },
            {   setting_id = "group_randomization_options_melee",
                type = "group",
                sub_widgets = {
                    {   setting_id = "group_randomization_options_body",
                        type = "group",
                        sub_widgets = {
                            {   setting_id = "mod_option_slim_blade_randomization",
                                type = "checkbox",
                                default_value = true,
                            },
                            {   setting_id = "mod_option_rear_spike_randomization",
                                type = "checkbox",
                                default_value = true,
                            },
                            {   setting_id = "group_randomization_options_chainsword",
                                type = "group",
                                sub_widgets = {
                                    {   setting_id = "mod_option_chainsword_blade_randomization",
                                        type = "checkbox",
                                        default_value = false,
                                    },
                                    {   setting_id = "mod_option_chainsword_chain_randomization",
                                        type = "checkbox",
                                        default_value = false,
                                    },
                                },
                            },
                        },
                    },
                },
            },
        }
	}
}
