url: "https://backup158.github.io/DarktideWeaponCustomizationOwO" # the base hostname & protocol for your site
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
markdown: GFM
