url: "https://backup158.github.io/DarktideWeaponCustomizationOwO" # the base hostname & protocol for your site
title: "Darktide Mod: Weapon Customization - OwO"
theme: 'jekyll-theme-slate'
markdown: GFM
